daftarLink = [['https://random-english-words.blogspot.com/','<img width="30px" height="auto" src="ukflag.png"/>Random English Words'],
	['https://swrdfgd.github.io/PunkRecords','📚Punk Records'],
	['https://randomarabicwords.blogspot.com/','<img width="30px" height="auto" src="arabflag.png"/>Random Arabic Words'],

	['https://swrdfgd.github.io/RandomYoutubeVideos/','📺Random Youtube Video'],
	['https://swrdfgd.github.io/BelajarMembaca/','📖Belajar Membaca Huruf Latin Generator'],
	//['https://www.knkland.com/p/ruang-koding.html','💻Ruang Koding'],
	//['https://internetmainmenu.blogspot.com/','🌐Internet Main Menu'],
	['https://swrdfgd.github.io/HiraganaPractice/','<img width="30px" height="auto" src="jpflag.png"/>Hiragana Practice'],
	['https://swrdfgd.github.io/KatakanaPractice/','<img width="30px" height="auto" src="jpflag.png"/>Katakana Practice'],
	['https://swrdfgd.github.io/RandomWebsite/','🌐🏄Random Website List'],


	['https://swrdfgd.github.io/HiraKataPractice/','<img width="30px" height="auto" src="jpflag.png"/>Hiragana and Katakana Practice'],
	['https://swrdfgd.github.io/StringPermutation','🔡🔄String Permutations Generator'],
	['https://swrdfgd.github.io/RandomImgur/','🖼Random Imgur Image Generator'],

	
	['https://frk-tal.blogspot.com/2022/08/random-plants-vs-zombies-2-plants.html','🌱🧟Random Plants Vs Zombies 2 Plants Generator'],
	['https://frk-tal.blogspot.com/2022/08/random-substance-generator.html','⚗Random Substance Generator'],
	['https://frk-tal.blogspot.com/2022/08/random-graph-generator.html','🖍Random Graph Generator'],
	//['https://frk-tal.blogspot.com/2022/08/random-yugioh-card-generator.html','🎴Random Yugioh Card Generator'],
	['https://frk-tal.blogspot.com/2022/08/color-gradient-generator.html','🌈Random Color Gradient Generator'],

	['https://frk-tal.blogspot.com/2022/07/random-compound-generator.html','🧪Random Compound Generator'],
	['https://frk-tal.blogspot.com/2023/01/random-species-generator.html','🐜Random Species Generator'],
	['https://www.knkland.com/p/kuisku.html','🧠Kuisku'],
	['https://swrdfgd.github.io/BraillePractice/','👩‍🦯👨‍🦯Braille Practice'],
	//['https://swrdfgd.github.io/RandomYugioh/','🎴Random Yugioh Card Generator'],
	['https://swrdfgd.github.io/MakhlukWorld/','🕶️Makhluk World'],
	['https://frk-tal.blogspot.com/2021/10/euclidean-algorithm-calculator-finding.html','🔢Euclidean Algorithm Calculator'],
	['https://swrdfgd.github.io/NumGen/','🔢Random Number Generator'],
	['https://swrdfgd.github.io/AreaZeroZero/','(0,0) Area ZeroZero'],

	['https://swrdfgd.github.io/RandomOnePiece/','🏴‍☠️Random One Piece Character'],
	['https://swrdfgd.github.io/RandomImage/','🖼️Random Image Generator'],
	['https://swrdfgd.github.io/RandomWords2/','💬Random Words'],
	['https://swrdfgd.github.io/RandomFood/','🍖Random Food Generator'],
	['https://swrdfgd.github.io/RandomPattern/indexTimedBackground.html','▩Random Pattern'],
	['https://swrdfgd.github.io/GraphSketcher/','✏️Graph Sketcher'],
	['https://swrdfgd.github.io/LearnTyping/','⌨️Learn Typing'],
	['https://swrdfgd.github.io/mathZpace/','🔢🌌mathZpace'],

	['https://swrdfgd.github.io/PrimeFactor/','🧮Prime Factorization Calculator'],
	['https://swrdfgd.github.io/SearchAnywhere/','🔍Search Anywhere'],
	['https://swrdfgd.github.io/RPST3/','✊✋✌️Rock Paper Scissor Tic Tac Toe Fusion'],
	['https://swrdfgd.github.io/RandomQuranVerse/','🌙🕌Random Quran Verse'],
	['https://swrdfgd.github.io/GimmeThings/','🤲Gimme Things'],
	['https://swrdfgd.github.io/RandomChineseChar/','🀄Random Chinese Character Generator'],
	['https://swrdfgd.github.io/EmojiScreenSaver/','🖥️Emoji Screen Saver'],
	['https://swrdfgd.github.io/TodayVibe/','☕Today Vibe'],
	['https://swrdfgd.github.io/ScreenSaver/','🔤Flying Characters Screen Saver'],
	['https://swrdfgd.github.io/RandomMathVideos/','🎥📚🔢Random Math Videos'],

	['https://swrdfgd.github.io/MathKeywords/','🎥📚🔢Random Math Keywords'],
	['https://swrdfgd.github.io/RandomSeating/','🪑Random Seating Allocation Generator'],
	['https://swrdfgd.github.io/RandomSubset/','🎲🔢Random Subset Generator'],
	['https://swrdfgd.github.io/LandOfKindness/','💗Land of Kindness'],
	['https://swrdfgd.github.io/LandOfKnowledge/','🌐Land of Knowledge'],
	['https://swrdfgd.github.io/RandomMatrix/','🎲🔢Random Matrix Generator'],
	['http://cointiply.com/r/3xgnG','<img width="30px" height="auto" src="bitcoin.png"/>Free Bitcoin'],
	['https://swrdfgd.github.io/RandomLinks/','🎲🌐Random Links Generator'],
	['https://swrdfgd.github.io/RandomImageLottery/','🎰Random Image Lottery'],
	['https://swrdfgd.github.io/Planets/','🪐Planets'],
	['https://swrdfgd.github.io/EmojiTyping/','😎Emoji Typing'],
	['https://swrdfgd.github.io/Weirdtris/','🕹️Weirdtris'],
	['https://swrdfgd.github.io/RandomStackQuestion/','❓️Random StackExchange Question'],
	['http://swrdfgd.github.io/RandomGithub','👾Random Github Repository'],
	['https://swrdfgd.github.io/LandOfFreedom','🕊️Land of Freedom'],
	['https://swrdfgd.github.io/RandomInstagram','🦋⃝Random Instagram Reel'],
	['https://swrdfgd.github.io/RandomWiki','🚀Random Wiki Article'],
	['https://swrdfgd.github.io/PokemonOnet/','<img width="30px" height="auto" src="pokeball.png"/>Pokemon Onet'],
	];