document.addEventListener("DOMContentLoaded", function() {
    // Cari SEMUA elemen yang memiliki class "iklanan"
    const semuaElemenIklan = document.querySelectorAll(".iklanan");

        // 1. Array khusus untuk iklan Horizontal
        const iklanHorizontal = [
			[`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/125x125/simple_v1.gif" alt="Advertise with Anonymous Ads" width="125px" height="125px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/200x200/simple_v1.gif" alt="Advertise with Anonymous Ads" width="200px" height="200px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/250x250/simple_v1.gif" alt="Advertise with Anonymous Ads" width="250px" height="250px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/300x250/simple_v1.gif" alt="Advertise with Anonymous Ads" width="300px" height="250px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/320x50/simple_v1.gif" alt="Advertise with Anonymous Ads" width="320px" height="50px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/320x100/simple_v1.gif" alt="Advertise with Anonymous Ads" width="320px" height="100px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/336x280/simple_v1.gif" alt="Advertise with Anonymous Ads" width="336px" height="280px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/468x60/simple_v1.gif" alt="Advertise with Anonymous Ads" width="468px" height="60px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/728x90/simple_v1.gif" alt="Advertise with Anonymous Ads" width="728px" height="90px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/970x90/simple_v1.gif" alt="Advertise with Anonymous Ads" width="970px" height="90px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/970x250/simple_v1.gif" alt="Advertise with Anonymous Ads" width="970px" height="250px" /></a>`,
			],
			[
			`<!-- BEGIN AADS AD UNIT 2450840 --> <div id="frame" style="width: 100%;margin: auto;position: relative; z-index: 99998;"> <iframe data-aa='2450840' src='//acceptable.a-ads.com/2450840/?size=Adaptive' style='border:0; padding:0; width:70%; height:auto; overflow:hidden;display: block;margin: auto'></iframe> </div> <!-- END AADS AD UNIT 2450840 -->`,
			],
			[`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/1_300x250.png" alt="" width="300" height="250"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/1_300x300.png" alt="" width="300" height="300"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/1_320x50.png" alt="" width="320" height="50"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/1_320x100.png" alt="" width="320" height="100"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/1_324x60.png" alt="" width="324" height="60"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/1_336x280.png" alt="" width="336" height="280"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/1_468x60.png" alt="" width="468" height="60"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/1_728x90.png" alt="" width="728" height="90"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/2_300x250.png" alt="" width="300" height="250"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/2_300x300.png" alt="" width="300" height="300"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/2_320x50.png" alt="" width="320" height="50"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/2_320x100.png" alt="" width="320" height="100"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/2_324x60.png" alt="" width="324" height="60"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/2_336x280.png" alt="" width="336" height="280"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/2_468x60.png" alt="" width="468" height="60"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/2_728x90.png" alt="" width="728" height="90"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/gif/300x250.gif" alt="" width="300" height="250"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/gif/300x300.gif" alt="" width="300" height="300"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/gif/320x50.gif" alt="" width="320" height="50"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/gif/320x100.gif" alt="" width="320" height="100"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/gif/324x60.gif" alt="" width="324" height="60"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/gif/336x280.gif" alt="" width="336" height="280"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/gif/468x60.gif" alt="" width="468" height="60"/></a>`,
			`<iframe src="//api.fpadserver.com/referral-banners?size=234x60&clickTag=https://faucetpay.io/?r=16364" scrolling="no" frameborder="0" width="234" height="60"></iframe>`,
			`<iframe src="//api.fpadserver.com/referral-banners?size=300x250&clickTag=https://faucetpay.io/?r=16364" scrolling="no" frameborder="0" width="300" height="250"></iframe>`,
			`<iframe src="//api.fpadserver.com/referral-banners?size=300x300&clickTag=https://faucetpay.io/?r=16364" scrolling="no" frameborder="0" width="300" height="300"></iframe>`,
			`<iframe src="//api.fpadserver.com/referral-banners?size=320x50&clickTag=https://faucetpay.io/?r=16364" scrolling="no" frameborder="0" width="320" height="50"></iframe>`,
			`<iframe src="//api.fpadserver.com/referral-banners?size=320x100&clickTag=https://faucetpay.io/?r=16364" scrolling="no" frameborder="0" width="320" height="100"></iframe>`,
			`<iframe src="//api.fpadserver.com/referral-banners?size=336x280&clickTag=https://faucetpay.io/?r=16364" scrolling="no" frameborder="0" width="336" height="280"></iframe>`,
			`<iframe src="//api.fpadserver.com/referral-banners?size=468x60&clickTag=https://faucetpay.io/?r=16364" scrolling="no" frameborder="0" width="468" height="60"></iframe>`,
			`<iframe src="//api.fpadserver.com/referral-banners?size=728x90&clickTag=https://faucetpay.io/?r=16364" scrolling="no" frameborder="0" width="728" height="90"></iframe>`,
			],
			[`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w200h200.gif" alt="200h200"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w200h200.gif" alt="200h200"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w250h250.gif" alt="250h250"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w250h250.gif" alt="250h250"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w300h250.gif" alt="300h250"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w300h250.gif" alt="300h250"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w320h50.gif" alt="320h50"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w320h50.gif" alt="320h50"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w320h100.gif" alt="320h100"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w320h100.gif" alt="320h100"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w320h320.gif" alt="320h320"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w320h320.gif" alt="320h320"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w460h60.gif" alt="460h60"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w460h60.gif" alt="460h60"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w728h90.gif" alt="728h90"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w728h90.gif" alt="728h90"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w970h90.gif" alt="970h90"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w970h90.gif" alt="970h90"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w970h250.gif" alt="970h250"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w970h250.gif" alt="970h250"/> </a> <!--End rollercoin.com code-->`,
			],
			[`<a href="https://ref.adbtc.top/1403330" target="_blank" border="0"><img src="https://adbtc.top/promo/banner_728x90.png"/></a>`,
			`<a href="https://ref.adbtc.top/1403330" target="_blank" border="0"><img src="https://adbtc.top/promo/banner_468x60.jpg"/></a>`,
			`<a href="https://ref.adbtc.top/1403330" target="_blank" border="0"><img src="https://adbtc.top/promo/banner_250x250.png"/></a>`,
			`<a href="https://ref.adbtc.top/1403330" target="_blank" border="0"><img src="https://adbtc.top/promo/banner_728x90_2.png"/></a>`,
			],
			[`<a href="https://earnbitmoon.club/?ref=1314309" target="_blank"><img src="https://earnbitmoon.club/promo/EBM-728x90.gif" alt="Earnbitmoon" border="0" /></a>`,
			`<a href="https://earnbitmoon.club/?ref=1314309" target="_blank"><img src="https://earnbitmoon.club/promo/EBM_shiba_728.gif" alt="Earnbitmoon" border="0" /></a>`,
			`<a href="https://earnbitmoon.club/?ref=1314309" target="_blank"><img src="https://earnbitmoon.club/promo/EBM-468x60.gif" alt="Earnbitmoon" border="0" /></a>`,
			`<a href="https://earnbitmoon.club/?ref=1314309" target="_blank"><img src="https://earnbitmoon.club/promo/EBM-300x250.gif" alt="Earnbitmoon" border="0" /></a>`,
			`<a href="https://earnbitmoon.club/?ref=1314309" target="_blank"><img src="https://earnbitmoon.club/promo/EBM_shiba_300.gif" alt="Earnbitmoon" border="0" /></a>`,
			],
			[`<a href="https://viefaucet.com?r=6a75dd59ceaac88d244f0894" target="_blank" rel="noopener noreferrer"> <img src="https://viefaucet.com/banners/300x250.gif" alt="Vie Faucet Banner" width="300" height="250" style="border: none;" /> </a>`,
			],
			[`<a href="https://indodax.com/ref/Swordofgod/1" target="_blank"> <img src="https://swrdfgd.github.io/indodax/horizontal-688x384.jpg" alt="Indodax Banner" width="344" height="192" style="border: none;" /> </a>`,
			`<a href="https://indodax.com/ref/Swordofgod/1" target="_blank"> <img src="https://swrdfgd.github.io/indodax/persegi-512x512.jpg" alt="Indodax Banner" width="256" height="256" style="border: none;" /> </a>`,
			],
			[`<a href="https://claimfreecoins.io/zcash-faucet/?r=syaiftheoplover1925@gmail.com" target="_blank" style="display: flex; flex-direction: column; width: 250px; height: 250px; text-decoration: none; border: 1px solid #e0e0e0; font-family: 'Segoe UI', Arial, sans-serif; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden; transition: transform 0.2s ease-in-out;" onmouseover="this.style.transform='scale(1.02)';" onmouseout="this.style.transform='scale(1)';"> <div style="background-color: #000000; color: #ffffff; height: 45%; display: flex; align-items: center; justify-content: center; text-align: center; padding: 10px;"> <span style="font-size: 24px; font-weight: bold; line-height: 1.2;">Free Zcash<br>Faucet</span> </div> <div style="background-color: #ffffff; color: #333333; height: 55%; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; padding: 15px; box-sizing: border-box;"> <span style="font-size: 18px; font-weight: 800; color: #f4b728; margin-bottom: 8px; text-transform: uppercase;">Claim Now</span> <span style="font-size: 12px; color: #666666; margin-bottom: 12px;">Get free Zcash directly to your crypto wallet!</span> <span style="background-color: #f4b728; color: #000000; padding: 6px 16px; border-radius: 20px; font-size: 13px; font-weight: bold;">Claim Here &rarr;</span> </div> </a>`,
			`<a href="https://claimfreecoins.io/ripple-faucet/?r=syaiftheoplover1925@gmail.com" target="_blank" style="display: flex; flex-direction: column; width: 250px; height: 250px; text-decoration: none; border: 1px solid #e0e0e0; font-family: 'Segoe UI', Arial, sans-serif; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden; transition: transform 0.2s ease-in-out;" onmouseover="this.style.transform='scale(1.02)';" onmouseout="this.style.transform='scale(1)';"> <div style="background-color: #000000; color: #ffffff; height: 45%; display: flex; align-items: center; justify-content: center; text-align: center; padding: 10px;"> <span style="font-size: 24px; font-weight: bold; line-height: 1.2;">Free XRP<br>Faucet</span> </div> <div style="background-color: #ffffff; color: #333333; height: 55%; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; padding: 15px; box-sizing: border-box;"> <span style="font-size: 18px; font-weight: 800; color: #f4b728; margin-bottom: 8px; text-transform: uppercase;">Claim Now</span> <span style="font-size: 12px; color: #666666; margin-bottom: 12px;">Get free Ripple directly to your crypto wallet!</span> <span style="background-color: #f4b728; color: #000000; padding: 6px 16px; border-radius: 20px; font-size: 13px; font-weight: bold;">Claim Here &rarr;</span> </div> </a>`,
			],
			[`<a href="https://earncryptowrs.in/?r=1343" target="_blank" style="display: flex; flex-direction: column; width: 250px; height: 250px; text-decoration: none; border: 1px solid #e0e0e0; font-family: 'Segoe UI', Arial, sans-serif; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden; transition: transform 0.2s ease-in-out;" onmouseover="this.style.transform='scale(1.02)';" onmouseout="this.style.transform='scale(1)';"> <div style="background-color: #000000; color: #ffffff; height: 45%; display: flex; align-items: center; justify-content: center; text-align: center; padding: 10px;"> <span style="font-size: 24px; font-weight: bold; line-height: 1.2;">Free Dash<br>Faucet</span> </div> <div style="background-color: #ffffff; color: #333333; height: 55%; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; padding: 15px; box-sizing: border-box;"> <span style="font-size: 18px; font-weight: 800; color: #f4b728; margin-bottom: 8px; text-transform: uppercase;">Claim Now</span> <span style="font-size: 12px; color: #666666; margin-bottom: 12px;">Get free Dash directly to your crypto wallet!</span> <span style="background-color: #f4b728; color: #000000; padding: 6px 16px; border-radius: 20px; font-size: 13px; font-weight: bold;">Claim Here &rarr;</span> </div> </a>`,
			`<a href="https://earncryptowrs.in/?r=1343" target="_blank" style="display: flex; flex-direction: column; width: 250px; height: 250px; text-decoration: none; border: 1px solid #e0e0e0; font-family: 'Segoe UI', Arial, sans-serif; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden; transition: transform 0.2s ease-in-out;" onmouseover="this.style.transform='scale(1.02)';" onmouseout="this.style.transform='scale(1)';"> <div style="background-color: #000000; color: #ffffff; height: 45%; display: flex; align-items: center; justify-content: center; text-align: center; padding: 10px;"> <span style="font-size: 24px; font-weight: bold; line-height: 1.2;">Free USDT<br>Faucet</span> </div> <div style="background-color: #ffffff; color: #333333; height: 55%; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; padding: 15px; box-sizing: border-box;"> <span style="font-size: 18px; font-weight: 800; color: #f4b728; margin-bottom: 8px; text-transform: uppercase;">Claim Now</span> <span style="font-size: 12px; color: #666666; margin-bottom: 12px;">Get free USDT directly to your crypto wallet!</span> <span style="background-color: #f4b728; color: #000000; padding: 6px 16px; border-radius: 20px; font-size: 13px; font-weight: bold;">Claim Here &rarr;</span> </div> </a>`,
			`<a href="https://earncryptowrs.in/?r=1343" target="_blank" style="display: flex; flex-direction: column; width: 250px; height: 250px; text-decoration: none; border: 1px solid #e0e0e0; font-family: 'Segoe UI', Arial, sans-serif; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden; transition: transform 0.2s ease-in-out;" onmouseover="this.style.transform='scale(1.02)';" onmouseout="this.style.transform='scale(1)';"> <div style="background-color: #000000; color: #ffffff; height: 45%; display: flex; align-items: center; justify-content: center; text-align: center; padding: 10px;"> <span style="font-size: 24px; font-weight: bold; line-height: 1.2;">Free DigiByte (DGB)<br>Faucet</span> </div> <div style="background-color: #ffffff; color: #333333; height: 55%; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; padding: 15px; box-sizing: border-box;"> <span style="font-size: 18px; font-weight: 800; color: #f4b728; margin-bottom: 8px; text-transform: uppercase;">Claim Now</span> <span style="font-size: 12px; color: #666666; margin-bottom: 12px;">Get free DigiByte (DGB) directly to your crypto wallet!</span> <span style="background-color: #f4b728; color: #000000; padding: 6px 16px; border-radius: 20px; font-size: 13px; font-weight: bold;">Claim Here &rarr;</span> </div> </a>`,
			],
			[`<a href="https://althub.club/r/115587" target="_blank"> <img src="https://althub.club/cdn/img/ad728x90.png" alt="Althub Banner" style="border: none;" /> </a>`,
			],
			[`<div style="width: 320px; height: 320px; background: linear-gradient(135deg, #e52d27, #b31217); color: #ffffff; border-radius: 16px; display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center; padding: 25px; box-sizing: border-box; box-shadow: 0 8px 20px rgba(0, 0, 0, 0.2); font-family: Arial, sans-serif; margin: 10px auto;"> <h3 style="margin: 0; font-size: 16px; color: #ffde00; text-transform: uppercase; letter-spacing: 2px;">Hadiah TUNAI</h3> <div style="font-size: 42px; font-weight: 900; margin: 10px 0; line-height: 1.1; text-shadow: 2px 2px 4px rgba(0,0,0,0.3);">Rp270rb lagi menunggumu!<br></div> <p style="font-size: 14px; margin: 0 0 20px 0; color: #f8f8f8; line-height: 1.4;">Jangan lewatkan kesempatan emas ini. Klaim Sekarang.</p> <a href="https://vpkami.com/uscSc" target="_blank" style="display: inline-block; background-color: #ffde00; color: #b31217; font-size: 16px; font-weight: bold; text-decoration: none; padding: 12px 25px; border-radius: 30px; transition: all 0.3s ease; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);" onmouseover="this.style.transform='scale(1.05)'; this.style.backgroundColor='#fff200'; this.style.boxShadow='0 6px 15px rgba(0, 0, 0, 0.4)';" onmouseout="this.style.transform='scale(1)'; this.style.backgroundColor='#ffde00'; this.style.boxShadow='0 4px 10px rgba(0, 0, 0, 0.3)';"> KLIK DI SINI </a> </div>`,
			`<div style="width: 320px; background: linear-gradient(135deg, #e52d27, #b31217); color: #ffffff; border-radius: 16px; display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center; padding: 25px; box-sizing: border-box; box-shadow: 0 8px 20px rgba(0, 0, 0, 0.2); font-family: Arial, sans-serif; margin: 10px auto;"> <h3 style="margin: 0; font-size: 16px; color: #ffde00; text-transform: uppercase; letter-spacing: 2px;">Hai bestie, ada aplikasi Easycash untuk solusi keuanganmu nih!</h3> <div style="font-size: 42px; font-weight: 900; margin: 10px 0; line-height: 1.1; text-shadow: 2px 2px 4px rgba(0,0,0,0.3);">Dana siap cair sekarang hingga Rp50 JUTA.<br></div> <p style="font-size: 14px; margin: 0 0 20px 0; color: #f8f8f8; line-height: 1.4;">Yuk cek aplikasi untuk dapat hadiah tunai GRATIS Rp70 RIBU. Di Easycash, bunga harian rendah banget dan tenor pembayaran panjang lho! Tunggu apalagi? </p> <a href="https://web.easycash.id/webview/activity/register-human-v2?code=KlPP9QSL&v=tab" target="_blank" style="display: inline-block; background-color: #ffde00; color: #b31217; font-size: 16px; font-weight: bold; text-decoration: none; padding: 12px 25px; border-radius: 30px; transition: all 0.3s ease; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);" onmouseover="this.style.transform='scale(1.05)'; this.style.backgroundColor='#fff200'; this.style.boxShadow='0 6px 15px rgba(0, 0, 0, 0.4)';" onmouseout="this.style.transform='scale(1)'; this.style.backgroundColor='#ffde00'; this.style.boxShadow='0 4px 10px rgba(0, 0, 0, 0.3)';"> KLIK DI SINI </a> </div>`,
			],
			[`<a href="https://freeusdcoin.com/?ref=148742" target="_blank"> <img src="https://freeusdcoin.com/img/freeusdcoin/banners/Banner728x90.jpg" alt="Free USD Coin" style="border: none;" /> </a>`,
			`<a href="https://freeusdcoin.com/?ref=148742" target="_blank"> <img src="https://freeusdcoin.com/img/freeusdcoin/banners/Banner468x60.jpg" alt="Free USD Coin" style="border: none;" /> </a>`,
			],
			[
			`<a href="https://www.easygoingfaucet.com/ref/syaiftheoplover1925%40gmail.com" target="_blank" style="display: flex; flex-direction: column; width: 250px; height: 250px; text-decoration: none; border: 1px solid #e0e0e0; font-family: 'Segoe UI', Arial, sans-serif; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden; transition: transform 0.2s ease-in-out;" onmouseover="this.style.transform='scale(1.02)';" onmouseout="this.style.transform='scale(1)';"> <div style="background-color: #000000; color: #ffffff; height: 45%; display: flex; align-items: center; justify-content: center; text-align: center; padding: 10px;"> <span style="font-size: 24px; font-weight: bold; line-height: 1.2;">Claim free<br>crypto</span> </div> <div style="background-color: #ffffff; color: #333333; height: 55%; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; padding: 15px; box-sizing: border-box;"> <span style="font-size: 18px; font-weight: 800; color: #f4b728; margin-bottom: 8px; text-transform: uppercase;">Claim Now</span> <span style="font-size: 12px; color: #666666; margin-bottom: 12px;">Login with your crypto address. Solve a quick captcha. Get paid. That's it.</span> <span style="background-color: #f4b728; color: #000000; padding: 6px 16px; border-radius: 20px; font-size: 13px; font-weight: bold;">Claim Here &rarr;</span> </div> </a>`,
			],
			[
			`<a href="https://propush.me/?ref_id=tYtK" target="_blank"><img src="https://swrdfgd.github.io/moreBanner/propushme.png" alt="Propush me" border="0" /></a>`,
			],
			[
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w320h320.png" alt="Promo banner" width="320" height="320"> </a>`,
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w300h250.png" alt="Promo banner" width="300" height="250"> </a>`,
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w250h250.png" alt="Promo banner" width="250" height="250"> </a>`,
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w200h200.png" alt="Promo banner" width="200" height="200"> </a>`,
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w970h250.png" alt="Promo banner" width="970" height="250"> </a>`,
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w970h90.png" alt="Promo banner" width="970" height="90"> </a>`,
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w728h90.png" alt="Promo banner" width="728" height="90"> </a>`,
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w460h60.png" alt="Promo banner" width="460" height="60"> </a>`,
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w320h100.png" alt="Promo banner" width="320" height="100"> </a>`,
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w320h50.png" alt="Promo banner" width="320" height="50"> </a>`,
			],
        ];

        // 2. Array khusus untuk iklan Vertikal
        const iklanVertikal = [
			[`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/120x600/simple_v1.gif" alt="Advertise with Anonymous Ads" width="120px" height="600px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/125x125/simple_v1.gif" alt="Advertise with Anonymous Ads" width="125px" height="125px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/160x600/simple_v1.gif" alt="Advertise with Anonymous Ads" width="160px" height="600px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/200x200/simple_v1.gif" alt="Advertise with Anonymous Ads" width="200px" height="200px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/240x400/simple_v1.gif" alt="Advertise with Anonymous Ads" width="240px" height="400px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/250x250/simple_v1.gif" alt="Advertise with Anonymous Ads" width="250px" height="250px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/300x250/simple_v1.gif" alt="Advertise with Anonymous Ads" width="300px" height="250px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/300x600/simple_v1.gif" alt="Advertise with Anonymous Ads" width="300px" height="600px" /></a>`,
			`<a href="https://aads.com/advertise/?partner=1202019"><img src="https://aads.com/a_ads_banners/gif/english/336x280/simple_v1.gif" alt="Advertise with Anonymous Ads" width="336px" height="280px" /></a>`,
			],
			[
			`<!-- BEGIN AADS AD UNIT 2450840 --> <div id="frame" style="width: 100%;margin: auto;position: relative; z-index: 99998;"> <iframe data-aa='2450840' src='//acceptable.a-ads.com/2450840/?size=Adaptive' style='border:0; padding:0; width:70%; height:auto; overflow:hidden;display: block;margin: auto'></iframe> </div> <!-- END AADS AD UNIT 2450840 -->`,
			],
			[`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/1_120x600.png" alt="" width="120" height="600"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/1_160x600.png" alt="" width="160" height="600"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/1_300x250.png" alt="" width="300" height="250"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/1_300x300.png" alt="" width="300" height="300"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/1_336x280.png" alt="" width="336" height="280"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/2_120x600.png" alt="" width="120" height="600"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/2_160x600.png" alt="" width="160" height="600"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/2_300x250.png" alt="" width="300" height="250"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/2_300x300.png" alt="" width="300" height="300"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/static/2_336x280.png" alt="" width="336" height="280"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/gif/120x600.gif" alt="" width="120" height="600"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/gif/160x600.gif" alt="" width="160" height="600"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/gif/300x250.gif" alt="" width="300" height="250"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/gif/300x300.gif" alt="" width="300" height="300"/></a>`,
			`<a href="https://faucetpay.io/?r=16364" target="_blank"><img src="https://cdn.faucetpay.io/banners/gif/336x280.gif" alt="" width="336" height="280"/></a>`,
			`<iframe src="//api.fpadserver.com/referral-banners?size=120x600&clickTag=https://faucetpay.io/?r=16364" scrolling="no" frameborder="0" width="120" height="600"></iframe>`,
			`<iframe src="//api.fpadserver.com/referral-banners?size=160x600&clickTag=https://faucetpay.io/?r=16364" scrolling="no" frameborder="0" width="160" height="600"></iframe>`,
			`<iframe src="//api.fpadserver.com/referral-banners?size=300x250&clickTag=https://faucetpay.io/?r=16364" scrolling="no" frameborder="0" width="300" height="250"></iframe>`,
			`<iframe src="//api.fpadserver.com/referral-banners?size=300x300&clickTag=https://faucetpay.io/?r=16364" scrolling="no" frameborder="0" width="300" height="300"></iframe>`,
			`<iframe src="//api.fpadserver.com/referral-banners?size=336x280&clickTag=https://faucetpay.io/?r=16364" scrolling="no" frameborder="0" width="336" height="280"></iframe>`,
			],
			[`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w120h240.gif" alt="120h240"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w120h240.gif" alt="120h240"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w120h600.gif" alt="120h600"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w120h600.gif" alt="120h600"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w160h600.gif" alt="160h600"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w160h600.gif" alt="160h600"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w200h200.gif" alt="200h200"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w200h200.gif" alt="200h200"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w250h250.gif" alt="250h250"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w250h250.gif" alt="250h250"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w300h250.gif" alt="300h250"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w300h250.gif" alt="300h250"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w300h600.gif" alt="300h600"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w300h600.gif" alt="300h600"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen2/w300h1050.gif" alt="300h1050"/> </a> <!--End rollercoin.com code-->`,
			`<!--Start rollercoin.com code--> <a href="https://rollercoin.com/?r=jy4kc2py"> <img src="https://static.rollercoin.com/static/img/ref/gen3/w300h1050.gif" alt="300h1050"/> </a> <!--End rollercoin.com code-->`,
			],
			[`<a href="https://ref.adbtc.top/1403330" target="_blank" border="0"><img src="https://adbtc.top/promo/banner_250x250.png"/></a>`,
			],
			[`<a href="https://earnbitmoon.club/?ref=1314309" target="_blank"><img src="https://earnbitmoon.club/promo/EBM-300x250.gif" alt="Earnbitmoon" border="0" /></a>`,
			`<a href="https://earnbitmoon.club/?ref=1314309" target="_blank"><img src="https://earnbitmoon.club/promo/EBM_shiba_300.gif" alt="Earnbitmoon" border="0" /></a>`,
			`<a href="https://earnbitmoon.club/?ref=1314309" target="_blank"><img src="https://earnbitmoon.club/promo/EBM-160x600.gif" alt="Earnbitmoon" border="0" /></a>`,
			],
			[`<a href="https://viefaucet.com?r=6a75dd59ceaac88d244f0894" target="_blank" rel="noopener noreferrer"> <img src="https://viefaucet.com/banners/300x250.gif" alt="Vie Faucet Banner" width="300" height="250" style="border: none;" /> </a>`,
			],
			[`<a href="https://indodax.com/ref/Swordofgod/1" target="_blank"> <img src="https://swrdfgd.github.io/indodax/vertikal-384x688.jpg" alt="Indodax Banner" width="192" height="344" style="border: none;" /> </a>`,
			`<a href="https://indodax.com/ref/Swordofgod/1" target="_blank"> <img src="https://swrdfgd.github.io/indodax/persegi-512x512.jpg" alt="Indodax Banner" width="256" height="256" style="border: none;" /> </a>`,
			],
			[`<a href="https://claimfreecoins.io/zcash-faucet/?r=syaiftheoplover1925@gmail.com" target="_blank" style="display: flex; flex-direction: column; width: 250px; height: 250px; text-decoration: none; border: 1px solid #e0e0e0; font-family: 'Segoe UI', Arial, sans-serif; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden; transition: transform 0.2s ease-in-out;" onmouseover="this.style.transform='scale(1.02)';" onmouseout="this.style.transform='scale(1)';"> <div style="background-color: #000000; color: #ffffff; height: 45%; display: flex; align-items: center; justify-content: center; text-align: center; padding: 10px;"> <span style="font-size: 24px; font-weight: bold; line-height: 1.2;">Free Zcash<br>Faucet</span> </div> <div style="background-color: #ffffff; color: #333333; height: 55%; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; padding: 15px; box-sizing: border-box;"> <span style="font-size: 18px; font-weight: 800; color: #f4b728; margin-bottom: 8px; text-transform: uppercase;">Claim Now</span> <span style="font-size: 12px; color: #666666; margin-bottom: 12px;">Get free Zcash directly to your crypto wallet!</span> <span style="background-color: #f4b728; color: #000000; padding: 6px 16px; border-radius: 20px; font-size: 13px; font-weight: bold;">Claim Here &rarr;</span> </div> </a>`,
			`<a href="https://claimfreecoins.io/ripple-faucet/?r=syaiftheoplover1925@gmail.com" target="_blank" style="display: flex; flex-direction: column; width: 250px; height: 250px; text-decoration: none; border: 1px solid #e0e0e0; font-family: 'Segoe UI', Arial, sans-serif; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden; transition: transform 0.2s ease-in-out;" onmouseover="this.style.transform='scale(1.02)';" onmouseout="this.style.transform='scale(1)';"> <div style="background-color: #000000; color: #ffffff; height: 45%; display: flex; align-items: center; justify-content: center; text-align: center; padding: 10px;"> <span style="font-size: 24px; font-weight: bold; line-height: 1.2;">Free XRP<br>Faucet</span> </div> <div style="background-color: #ffffff; color: #333333; height: 55%; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; padding: 15px; box-sizing: border-box;"> <span style="font-size: 18px; font-weight: 800; color: #f4b728; margin-bottom: 8px; text-transform: uppercase;">Claim Now</span> <span style="font-size: 12px; color: #666666; margin-bottom: 12px;">Get free Ripple directly to your crypto wallet!</span> <span style="background-color: #f4b728; color: #000000; padding: 6px 16px; border-radius: 20px; font-size: 13px; font-weight: bold;">Claim Here &rarr;</span> </div> </a>`,
			],
			[`<a href="https://earncryptowrs.in/?r=1343" target="_blank" style="display: flex; flex-direction: column; width: 250px; height: 250px; text-decoration: none; border: 1px solid #e0e0e0; font-family: 'Segoe UI', Arial, sans-serif; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden; transition: transform 0.2s ease-in-out;" onmouseover="this.style.transform='scale(1.02)';" onmouseout="this.style.transform='scale(1)';"> <div style="background-color: #000000; color: #ffffff; height: 45%; display: flex; align-items: center; justify-content: center; text-align: center; padding: 10px;"> <span style="font-size: 24px; font-weight: bold; line-height: 1.2;">Free Dash<br>Faucet</span> </div> <div style="background-color: #ffffff; color: #333333; height: 55%; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; padding: 15px; box-sizing: border-box;"> <span style="font-size: 18px; font-weight: 800; color: #f4b728; margin-bottom: 8px; text-transform: uppercase;">Claim Now</span> <span style="font-size: 12px; color: #666666; margin-bottom: 12px;">Get free Dash directly to your crypto wallet!</span> <span style="background-color: #f4b728; color: #000000; padding: 6px 16px; border-radius: 20px; font-size: 13px; font-weight: bold;">Claim Here &rarr;</span> </div> </a>`,
			`<a href="https://earncryptowrs.in/?r=1343" target="_blank" style="display: flex; flex-direction: column; width: 250px; height: 250px; text-decoration: none; border: 1px solid #e0e0e0; font-family: 'Segoe UI', Arial, sans-serif; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden; transition: transform 0.2s ease-in-out;" onmouseover="this.style.transform='scale(1.02)';" onmouseout="this.style.transform='scale(1)';"> <div style="background-color: #000000; color: #ffffff; height: 45%; display: flex; align-items: center; justify-content: center; text-align: center; padding: 10px;"> <span style="font-size: 24px; font-weight: bold; line-height: 1.2;">Free USDT<br>Faucet</span> </div> <div style="background-color: #ffffff; color: #333333; height: 55%; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; padding: 15px; box-sizing: border-box;"> <span style="font-size: 18px; font-weight: 800; color: #f4b728; margin-bottom: 8px; text-transform: uppercase;">Claim Now</span> <span style="font-size: 12px; color: #666666; margin-bottom: 12px;">Get free USDT directly to your crypto wallet!</span> <span style="background-color: #f4b728; color: #000000; padding: 6px 16px; border-radius: 20px; font-size: 13px; font-weight: bold;">Claim Here &rarr;</span> </div> </a>`,
			`<a href="https://earncryptowrs.in/?r=1343" target="_blank" style="display: flex; flex-direction: column; width: 250px; height: 250px; text-decoration: none; border: 1px solid #e0e0e0; font-family: 'Segoe UI', Arial, sans-serif; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden; transition: transform 0.2s ease-in-out;" onmouseover="this.style.transform='scale(1.02)';" onmouseout="this.style.transform='scale(1)';"> <div style="background-color: #000000; color: #ffffff; height: 45%; display: flex; align-items: center; justify-content: center; text-align: center; padding: 10px;"> <span style="font-size: 24px; font-weight: bold; line-height: 1.2;">Free DigiByte (DGB)<br>Faucet</span> </div> <div style="background-color: #ffffff; color: #333333; height: 55%; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; padding: 15px; box-sizing: border-box;"> <span style="font-size: 18px; font-weight: 800; color: #f4b728; margin-bottom: 8px; text-transform: uppercase;">Claim Now</span> <span style="font-size: 12px; color: #666666; margin-bottom: 12px;">Get free DigiByte (DGB) directly to your crypto wallet!</span> <span style="background-color: #f4b728; color: #000000; padding: 6px 16px; border-radius: 20px; font-size: 13px; font-weight: bold;">Claim Here &rarr;</span> </div> </a>`,
			],
			[`<div style="width: 320px; height: 320px; background: linear-gradient(135deg, #e52d27, #b31217); color: #ffffff; border-radius: 16px; display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center; padding: 25px; box-sizing: border-box; box-shadow: 0 8px 20px rgba(0, 0, 0, 0.2); font-family: Arial, sans-serif; margin: 10px auto;"> <h3 style="margin: 0; font-size: 16px; color: #ffde00; text-transform: uppercase; letter-spacing: 2px;">Hadiah TUNAI</h3> <div style="font-size: 42px; font-weight: 900; margin: 10px 0; line-height: 1.1; text-shadow: 2px 2px 4px rgba(0,0,0,0.3);">Rp270rb lagi menunggumu!<br></div> <p style="font-size: 14px; margin: 0 0 20px 0; color: #f8f8f8; line-height: 1.4;">Jangan lewatkan kesempatan emas ini. Klaim Sekarang.</p> <a href="https://vpkami.com/uscSc" target="_blank" style="display: inline-block; background-color: #ffde00; color: #b31217; font-size: 16px; font-weight: bold; text-decoration: none; padding: 12px 25px; border-radius: 30px; transition: all 0.3s ease; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);" onmouseover="this.style.transform='scale(1.05)'; this.style.backgroundColor='#fff200'; this.style.boxShadow='0 6px 15px rgba(0, 0, 0, 0.4)';" onmouseout="this.style.transform='scale(1)'; this.style.backgroundColor='#ffde00'; this.style.boxShadow='0 4px 10px rgba(0, 0, 0, 0.3)';"> KLIK DI SINI </a> </div>`,
			`<div style="width: 320px; background: linear-gradient(135deg, #e52d27, #b31217); color: #ffffff; border-radius: 16px; display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center; padding: 25px; box-sizing: border-box; box-shadow: 0 8px 20px rgba(0, 0, 0, 0.2); font-family: Arial, sans-serif; margin: 10px auto;"> <h3 style="margin: 0; font-size: 16px; color: #ffde00; text-transform: uppercase; letter-spacing: 2px;">Hai bestie, ada aplikasi Easycash untuk solusi keuanganmu nih!</h3> <div style="font-size: 42px; font-weight: 900; margin: 10px 0; line-height: 1.1; text-shadow: 2px 2px 4px rgba(0,0,0,0.3);">Dana siap cair sekarang hingga Rp50 JUTA.<br></div> <p style="font-size: 14px; margin: 0 0 20px 0; color: #f8f8f8; line-height: 1.4;">Yuk cek aplikasi untuk dapat hadiah tunai GRATIS Rp70 RIBU. Di Easycash, bunga harian rendah banget dan tenor pembayaran panjang lho! Tunggu apalagi? </p> <a href="https://web.easycash.id/webview/activity/register-human-v2?code=KlPP9QSL&v=tab" target="_blank" style="display: inline-block; background-color: #ffde00; color: #b31217; font-size: 16px; font-weight: bold; text-decoration: none; padding: 12px 25px; border-radius: 30px; transition: all 0.3s ease; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);" onmouseover="this.style.transform='scale(1.05)'; this.style.backgroundColor='#fff200'; this.style.boxShadow='0 6px 15px rgba(0, 0, 0, 0.4)';" onmouseout="this.style.transform='scale(1)'; this.style.backgroundColor='#ffde00'; this.style.boxShadow='0 4px 10px rgba(0, 0, 0, 0.3)';"> KLIK DI SINI </a> </div>`,
			],
			[
			`<a href="https://www.easygoingfaucet.com/ref/syaiftheoplover1925%40gmail.com" target="_blank" style="display: flex; flex-direction: column; width: 250px; height: 250px; text-decoration: none; border: 1px solid #e0e0e0; font-family: 'Segoe UI', Arial, sans-serif; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden; transition: transform 0.2s ease-in-out;" onmouseover="this.style.transform='scale(1.02)';" onmouseout="this.style.transform='scale(1)';"> <div style="background-color: #000000; color: #ffffff; height: 45%; display: flex; align-items: center; justify-content: center; text-align: center; padding: 10px;"> <span style="font-size: 24px; font-weight: bold; line-height: 1.2;">Claim free<br>crypto</span> </div> <div style="background-color: #ffffff; color: #333333; height: 55%; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; padding: 15px; box-sizing: border-box;"> <span style="font-size: 18px; font-weight: 800; color: #f4b728; margin-bottom: 8px; text-transform: uppercase;">Claim Now</span> <span style="font-size: 12px; color: #666666; margin-bottom: 12px;">Login with your crypto address. Solve a quick captcha. Get paid. That's it.</span> <span style="background-color: #f4b728; color: #000000; padding: 6px 16px; border-radius: 20px; font-size: 13px; font-weight: bold;">Claim Here &rarr;</span> </div> </a>`,
			],
			[
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w320h320.png" alt="Promo banner" width="320" height="320"> </a>`,
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w300h250.png" alt="Promo banner" width="300" height="250"> </a>`,
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w250h250.png" alt="Promo banner" width="250" height="250"> </a>`,
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w200h200.png" alt="Promo banner" width="200" height="200">`,
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w300h1050.png" alt="Promo banner" width="300" height="1050"> </a>`,
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w300h600.png" alt="Promo banner" width="300" height="600"> </a>`,
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w160h600.png" alt="Promo banner" width="160" height="600"> </a>`,
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w120h600.png" alt="Promo banner" width="120" height="600"> </a>`,
			`<a href="https://chainers.io?r=mtj6vuhc" target="_blank" rel="noopener noreferrer"> <img src="https://static.chainers.io/referralPromoMaterials/concept1/w120h240.png" alt="Promo banner" width="120" height="240"> </a>`,
			],
		];

    // 2. Jika ada elemen yang ditemukan, jalankan proses untuk masing-masing elemen
    if (semuaElemenIklan.length > 0) {
        semuaElemenIklan.forEach(function(elemen) {
            
            // Ambil format dari elemen yang sedang diproses
            const formatIklan = elemen.getAttribute("data-format");
            let arrayPilihan = [];

            // Tentukan array mana yang dipakai
            if (formatIklan === "horizontal") {
                arrayPilihan = iklanHorizontal;
            } else if (formatIklan === "vertikal") {
                arrayPilihan = iklanVertikal;
            } else {
                console.warn("Class 'iklanan' ditemukan, tapi data-format tidak valid/kosong.");
                return; // Lanjut ke elemen berikutnya
            }

            // Pilih iklan acak dan masukkan ke elemen tersebut
            if (arrayPilihan.length > 0) {
				const indeksAcak = Math.floor(Math.random() * arrayPilihan.length);
				const iklanPilihan = arrayPilihan[indeksAcak];
				const indeksAcak2 = Math.floor(Math.random() * iklanPilihan.length);
				elemen.innerHTML = iklanPilihan[indeksAcak2];
            }
        });
    } else {
        console.warn("Tidak ada elemen dengan class 'iklanan' di halaman ini.");
    }
});